### ISSUE TITLE
Filter by house

### ISSUE THREAD

**Issue by badabam** [badabam/harry-potter-app#4]
### Value proposition (user story)

As a **user**
I want to **filter by house**
in order to have a **better overview** who belongs together

### Description (text, scribble, design)

4 buttons for the houses, 1 button "no house" and a reset button

### Acceptance criteria (edge cases)

- [ ] styled as designed
- [ ] no button is selected as default 
- [ ] all characters are shown by default

### Complexity (S, M, L)
M

### Tasks

- [x] Create feature branch
- [x] Create Button component (storybook)
- [ ] Create Filter component (storybook)
- [ ] Add application logic
